# Generated by Django 4.2.2 on 2023-08-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_updateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
