# Generated by Django 4.2.2 on 2023-08-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_updateprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='tweetURL',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='category',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='hateCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='neutralCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='offensiveCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='weightage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='twitterUser',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
